// tslint:disable
/**
 * 中台API接口
 * 后端接口托管在YApi系统，地址：http://121.37.134.143:13000/。 这里的接口都是需要经过验证才能进入这个项目。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
